module.exports.carga1 = function() {

    'use strict'
    
    // Imports
    let Diccionario = require('../model/diccionario');
    let Mercado = require('../model/mercado');
 
    // Ejecutamos carga de Mercados
    new Mercado({ mercadoID: "BME", nombre: "Bolsa de Madrid", pais: "ES"} ).save();
    
    // Ejecutamos carga de Diccionarios

    // Indicadores
    new Diccionario({ tipo: "indicador" , tag: "Corto Plazo", valor: "Corto Plazo" }).save();
    new Diccionario({ tipo: "indicador" , tag: "Medio Plazo", valor: "Medio Plazo" }).save();
    new Diccionario({ tipo: "indicador" , tag: "Largo Plazo", valor: "Largo Plazo" }).save();
    new Diccionario({ tipo: "indicador" , tag: "RSI 7", valor: "RSI 7" }).save();
    new Diccionario({ tipo: "indicador" , tag: "RSI 14", valor: "RSI 14" }).save();
    new Diccionario({ tipo: "indicador" , tag: "RSI 50", valor: "RSI 50" }).save();
    new Diccionario({ tipo: "indicador" , tag: "RSI 200", valor: "RSI 200" }).save();
    new Diccionario({ tipo: "indicador" , tag: "Estoc. Rápidos", valor: "Estoc. Rápidos" }).save();
    new Diccionario({ tipo: "indicador" , tag: "Estoc. Lentos", valor: "Estoc. Lentos" }).save();
    new Diccionario({ tipo: "indicador" , tag: "MM 7", valor: "MM 7" }).save();
    new Diccionario({ tipo: "indicador" , tag: "MM 21", valor: "MM 21" }).save();
    new Diccionario({ tipo: "indicador" , tag: "MM 50", valor: "MM 50" }).save();
    new Diccionario({ tipo: "indicador" , tag: "MM 200", valor: "MM 200" }).save();
    new Diccionario({ tipo: "indicador" , tag: "EMM 7", valor: "EMM 7" }).save();
    new Diccionario({ tipo: "indicador" , tag: "EMM 21", valor: "EMM 21" }).save();
    new Diccionario({ tipo: "indicador" , tag: "EMM 50", valor: "EMM 50" }).save();
    new Diccionario({ tipo: "indicador" , tag: "EMM 200", valor: "EMM 200" }).save();
    new Diccionario({ tipo: "indicador" , tag: "MACD linea/señal", valor: "MACD" }).save();
    new Diccionario({ tipo: "indicador" , tag: "Bollinger 95", valor: "Bollinger 95" }).save();
    new Diccionario({ tipo: "indicador" , tag: "Bollinger 99", valor: "Bollinger 99" }).save();
    new Diccionario({ tipo: "indicador" , tag: "EMM Doble 7", valor: "EMM Doble 7" }).save();
    new Diccionario({ tipo: "indicador" , tag: "EMM Doble 21", valor: "EMM Doble 21" }).save();
    new Diccionario({ tipo: "indicador" , tag: "EMM Doble 50", valor: "EMM Doble 50" }).save();
    new Diccionario({ tipo: "indicador" , tag: "EMM Doble 200", valor: "EMM Doble 200" }).save();
    new Diccionario({ tipo: "indicador" , tag: "Divergencias", valor: "Divergencias" }).save();
    new Diccionario({ tipo: "indicador" , tag: "On Balance Vol.", valor: "On Balance Vol." }).save();
    new Diccionario({ tipo: "indicador" , tag: "Momento 7", valor: "Momento 7" }).save();
    new Diccionario({ tipo: "indicador" , tag: "Momento 14", valor: "Momento 14" }).save();
    new Diccionario({ tipo: "indicador" , tag: "% K Williams", valor: "% K Williams" }).save();    

    // Tickers expansion
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ABENGOA", valor: "ABG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ABENGOA", valor: "ABG.P" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ABERTIS", valor: "ABE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ACCIONA", valor: "ANA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ACERINOX", valor: "ACX" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ACS", valor: "ACS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ADOLFO DOMÍNGUEZ", valor: "ADZ" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ADVEO", valor: "ADV" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "AEDAS HOMES", valor: "AEDAS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "AENA", valor: "AENA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "AIRBUS", valor: "AIR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ALANTRA", valor: "ALNT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ALBA", valor: "ALB" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ALMIRALL", valor: "ALM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "AMADEUS IT GROUP", valor: "AMS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "AMPER", valor: "AMP" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "APERAM", valor: "APAM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "APPLUS", valor: "APPS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ARCELORMITTAL", valor: "MTS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ATRESMEDIA", valor: "A3M" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "AUDAX RENOVABLES", valor: "ADX" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "AXIARE PATRIMONIO SOCIMI", valor: "AXIA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "AZKOYEN", valor: "AZK" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "BANCO SABADELL", valor: "SAB" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "BANKIA", valor: "BKIA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "BANKINTER", valor: "BKT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "BARÓN DE LEY", valor: "BDL" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "BAVIERA", valor: "CBAV" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "BAYER", valor: "BAY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "BBVA", valor: "BBVA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "BIOSEARCH", valor: "BIO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "BME", valor: "BME" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "BODEGAS RIOJANAS", valor: "RIO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "BORGES AGRI BR", valor: "BAIN" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "C.A.F.", valor: "CAF" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "CAIXABANK", valor: "CABK" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "CAM", valor: "CAM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "CATALANA OCCIDENTE", valor: "GCO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "CELLNEX TELECOM", valor: "CLNX" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "CIE. AUTOMOTIVE", valor: "CIE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "CLEOP", valor: "CLEO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "COCA-COLA EUROP", valor: "CCE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "CODERE", valor: "CDR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "COEMAC", valor: "CMC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "COLONIAL", valor: "COL" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "DEOLEO", valor: "OLE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "DIA", valor: "DIA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "DOGI", valor: "DGI" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "DURO FELGUERA", valor: "MDF" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "EBRO FOODS", valor: "EBRO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "EDREAMS ODIGEO", valor: "EDR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ELECNOR", valor: "ENO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ENAGAS", valor: "ENG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ENCE", valor: "ENC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ENDESA", valor: "ELE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ERCROS", valor: "ECR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "EUROPAC", valor: "PAC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "EUSKALTEL", valor: "EKT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "EZENTIS", valor: "EZE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "FAES", valor: "FAE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "FCC", valor: "FCC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "FERROVIAL", valor: "FER" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "FLUIDRA", valor: "FDR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "FUNESPAÑA", valor: "FUN" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "GAM", valor: "GALQ" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "GAS NATURAL", valor: "NTGY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "NATURGY", valor: "NTGY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "GESTAMP", valor: "GEST" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "GLOBAL DOMINION ACCESS", valor: "DOM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "GRENERGY RENOVABLES", valor: "GRE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "GRIFOLS", valor: "GRF" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "GRUPO EMP. SAN JOSE", valor: "GSJ" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "HISPANIA ACTIVOS INMOBILIARIOS", valor: "HIS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "IAG", valor: "IAG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "IBERDROLA", valor: "IBE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "IBERPAPEL", valor: "IBG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "INDITEX", valor: "ITX" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "INDRA", valor: "IDR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "INMOBILIARIA DEL SUR", valor: "ISUR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "INYPSA", valor: "INY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "LABORATORIO REIG JOFRE", valor: "RJF" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "LAR ESPAÑA", valor: "LRE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "LIBERBANK", valor: "LBK" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "LINGOTES", valor: "LGT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "LOGISTA", valor: "LOG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "MAPFRE", valor: "MAP" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "MASMOVIL", valor: "MAS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "MEDIASET", valor: "TL5" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "MELIÁ HOTELS", valor: "MEL" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "MERLIN PROP.", valor: "MRL" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "METROVACESA", valor: "MVC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "MIQUEL COSTAS", valor: "MCM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "MONTEBALITO", valor: "MTB" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "NATRA", valor: "NAT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "NATURHOUSE HEALTH", valor: "NTH" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "NEINOR HOMES", valor: "HOME" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "NH HOTEL GROUP", valor: "NHH" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "NICOLÁS CORREA", valor: "NEA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "NYESA", valor: "NYE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "OHL", valor: "OHL" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ORYZON GENOMICS", valor: "ORY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "PARQUES REUNIDOS", valor: "PQR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "PESCANOVA", valor: "PVA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "PHARMA MAR", valor: "PHM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "PRIM", valor: "PRM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "PRISA", valor: "PRS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "PROSEGUR", valor: "PSG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "PROSEGUR CASH", valor: "CASH" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "QUABIT", valor: "QBT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "REALIA", valor: "RLIA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "RED ELÉCTRICA", valor: "REE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "RENO DE MEDICI", valor: "RDM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "RENTA CORPORACION", valor: "REN" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "RENTA 4", valor: "R4" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "REPSOL", valor: "REP" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ROVI", valor: "ROVI" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "SACYR", valor: "SCYR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "SAETA YIELD", valor: "SAY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "SANTANDER", valor: "SAN" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "SERVICE POINT", valor: "SPS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "SIEMENS GAMESA", valor: "SGRE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "SNIACE", valor: "SNC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "SOLARIA", valor: "SLR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "TALGO", valor: "TLGO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "TECNICAS REUNIDAS", valor: "TRE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "TELEFÓNICA", valor: "TEF" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "TELEPIZZA GROUP", valor: "TPZ" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "TUBACEX", valor: "TUB" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "TUBOS REUNIDOS", valor: "TRG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "UNICAJA BANCO", valor: "UNI" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "URBAS", valor: "UBS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "VERTICE", valor: "VER" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "VIDRALA", valor: "VID" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "VISCOFAN", valor: "VIS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "VOCENTO", valor: "VOC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "ZARDOYA OTIS", valor: "ZOT" }).save();

    // Tickers infomercados
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Abengoa", valor: "ABG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Abengoa B", valor: "ABG.P" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Abertis", valor: "ABE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Acciona", valor: "ANA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Acerinox", valor: "ACX" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Acs", valor: "ACS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Adolfo Dom.", valor: "ADZ" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Adveo Group", valor: "ADV" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Aena", valor: "AENA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Airbus", valor: "AIR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Alantra", valor: "ALNT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Alba Corp.", valor: "ALB" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Almirall", valor: "ALM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Amadeus", valor: "AMS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Amper", valor: "AMP" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Aperam", valor: "APAM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Arcelor Mitt", valor: "MTS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Atresmedia", valor: "A3M" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Fersa Energ.", valor: "ADX" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Axiare", valor: "AXIA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Azkoyen", valor: "AZK" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Banco Sabade", valor: "SAB" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Bankia", valor: "BKIA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Bankinter", valor: "BKT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Baron De Ley", valor: "BDL" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Cli. Baviera", valor: "CBAV" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Bayer", valor: "BAY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Bbva", valor: "BBVA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Bio Search", valor: "BIO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Bme", valor: "BME" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Bodegas Rioj", valor: "RIO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Auxil.ff.cc", valor: "CAF" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Caixabank", valor: "CABK" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "CAM", valor: "CAM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Catalana Oc.", valor: "GCO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Cellnex", valor: "CLNX" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Cie Automoti", valor: "CIE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Coca-cola Eu", valor: "CCE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Coemac", valor: "CMC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Colonial", valor: "COL" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Deoleo", valor: "OLE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Dia", valor: "DIA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Dogi", valor: "DGI" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "D.felguera", valor: "MDF" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Ebro Foods", valor: "EBRO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Edreams", valor: "EDR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Elecnor", valor: "ENO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Enagas", valor: "ENG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Ence", valor: "ENC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Endesa", valor: "ELE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Ercros", valor: "ECR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Europac", valor: "PAC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Euskaltel", valor: "EKT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Gr. Ezentis", valor: "EZE" }).save();  
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Faes", valor: "FAE" }).save();     
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "F.C.Contrata", valor: "FCC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Ferrovial", valor: "FER" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Fluidra S.A.", valor: "FDR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Funespa/a", valor: "FUN" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "GAM", valor: "GALQ" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Gas Natural", valor: "NTGY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Naturgy", valor: "NTGY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Gestamp Auto", valor: "GEST" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Dominion", valor: "DOM" }).save();  
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Grifols Sa", valor: "GRF" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "San José", valor: "GSJ" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Hispania", valor: "HIS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Iag", valor: "IAG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Iberdrola", valor: "IBE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Iberpapel", valor: "IBG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Inditex", valor: "ITX" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Indra", valor: "IDR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Inmobil. Sur", valor: "ISUR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Inypsa S.A.", valor: "INY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Lar España", valor: "LRE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Liberbank Sa", valor: "LBK" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Ling.Especia", valor: "LGT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Logista", valor: "LOG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Mapfre", valor: "MAP" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Mediaset Esp", valor: "TL5" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Meliá Hotels", valor: "MEL" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Merlin Prop", valor: "MRL" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Miquel Y C.", valor: "MCM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Montebalito", valor: "MTB" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Natra", valor: "NAT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Naturhouse", valor: "NTH" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Neinor Homes", valor: "HOME" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Nh Hoteles", valor: "NHH" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "N.correa", valor: "NEA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Nyesa", valor: "NYE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Obrascon H.L", valor: "OHL" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Oryzon", valor: "ORY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Par Reunidos", valor: "PQR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Pescanova", valor: "PVA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Pharma Mar", valor: "PHM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Prim", valor: "PRM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Prisa", valor: "PRS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Prosegur", valor: "PSG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Prosegur Cas", valor: "CASH" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Quabit", valor: "QBT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Realia", valor: "RLIA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Red Electric", valor: "REE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Reig Jofre", valor: "RDM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Reno Medici", valor: "RDM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Renta 4", valor: "R4" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Renta Corp.", valor: "REN" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Repsol Ypf", valor: "REP" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Rovi", valor: "ROVI" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Sacyr", valor: "SCYR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Santander Ce", valor: "SAN" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "S.p. Solutio", valor: "SPS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Gamesa", valor: "SGRE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Sniace", valor: "SNC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Solaria", valor: "SLR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Talgo", valor: "TLGO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Téc Reunidas", valor: "TRE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Telefonica", valor: "TEF" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Telepizza", valor: "TPZ" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Tubacex", valor: "TUB" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Tubos Reun.", valor: "TRG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Urbas", valor: "UBS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Vertice", valor: "VER" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Vidrala", valor: "VID" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Viscofan", valor: "VIS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Vocento", valor: "VOC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "infomercados" , tag: "Zardoya Otis", valor: "ZOT" }).save();

    // Tickers bolsamania
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ABENGOA BR-A", valor: "ABG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ABENGOA BR-B", valor: "ABG.P" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "Abertis", valor: "ABE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ACCIONA", valor: "ANA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ACERINOX", valor: "ACX" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ACS", valor: "ACS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ADOLFO DOMINGUEZ", valor: "ADZ" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ADVEO GROUP INTL", valor: "ADV" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "AENA", valor: "AENA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "AIRBUS", valor: "AIR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ALANTRA PART", valor: "ALNT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "CORP. FIN. ALBA", valor: "ALB" }).save();    
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ALMIRALL", valor: "ALM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "AMADEUS IT GRP BR-A", valor: "AMS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "AMPER", valor: "AMP" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "APERAM", valor: "APAM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "APPLUS SERVICES", valor: "APPS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ARCELORMITTAL", valor: "MTS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ATRESMEDIA", valor: "A3M" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "AUDAX RENOV", valor: "ADX" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "AXIARE PATRIMONI", valor: "AXIA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "AZKOYEN", valor: "AZK" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "BANCO SABADELL", valor: "SAB" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "BANKIA", valor: "BKIA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "BANKINTER", valor: "BKT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "BARON DE LEY", valor: "BDL" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "CLINICA BAVIERA", valor: "CBAV" }).save();   
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "BAYER N", valor: "BAY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "BBVA", valor: "BBVA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "BIOSEARCH", valor: "BIO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "BOLSAS Y MERCADO", valor: "BME" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "CONSTR AUXILIAR", valor: "CAF" }).save();    
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "Caixabank", valor: "CABK" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "CAM", valor: "CAM" }).save();          
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "GRUPO CATALANA O", valor: "GCO" }).save();   
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "CELLNEX TELECOM", valor: "CLNX" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "CIE AUTOMOTIVE", valor: "CIE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "CLEOP", valor: "CLEO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "COCA-COLA EUR", valor: "CCE" }).save(); 
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "COEMAC", valor: "CMC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "INMOB COLONIAL", valor: "COL" }).save(); 
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "DEOLEO", valor: "OLE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "Dia", valor: "DIA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "DOGI INT FABRICS", valor: "DGI" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "DURO FELGUERA", valor: "MDF" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "EBRO FOODS", valor: "EBRO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "EDREAMS ODIGEO", valor: "EDR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ELECNOR", valor: "ENO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ENAGAS", valor: "ENG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ENCE ENERGIA", valor: "ENC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ENDESA", valor: "ELE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ERCROS", valor: "ECR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "PAPELES Y CARTON", valor: "PAC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "EUSKALTEL", valor: "EKT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "GRUPO EZENTIS", valor: "EZE" }).save();  
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "FAES FARMA", valor: "FAE" }).save();     
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "FOMENTO CONSTR.", valor: "FCC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "Ferrovial", valor: "FER" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "FLUIDRA", valor: "FDR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "FUNESPANA", valor: "FUN" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "GAM", valor: "GALQ" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "NATURGY GRP", valor: "NTGY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "Naturgy", valor: "NTGY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "GLOBAL DOMINION", valor: "DOM" }).save();  
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "GRIFOLS-A", valor: "GRF" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "GRP EMPR S JOSE", valor: "GSJ" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "HISPANIA ACTIVOS", valor: "HIS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "INTL. CONS. AIR", valor: "IAG" }).save();       
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "Iberdrola", valor: "IBE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "IBERPAPEL", valor: "IBG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "Inditex", valor: "ITX" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "INDRA SISTEMAS BR-A", valor: "IDR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "INMOBILIARIA SUR", valor: "ISUR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "INYPSA", valor: "INY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "LAB.REIG JOFRE", valor: "RJF" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "LAR ESPANA", valor: "LRE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "LIBERBANK", valor: "LBK" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "LINGOTES ESPECIA", valor: "LGT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "MASMOVIL IBERCOM", valor: "MAS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "Mapfre", valor: "MAP" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "Mediaset Espa&amp;Atilde;&amp;plusmn;a", valor: "TL5" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "Melia Hotels", valor: "MEL" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "MERLIN PROP.", valor: "MRL" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "MIQUEL Y COSTAS", valor: "MCM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "MONTEBALITO", valor: "MTB" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "NATRA", valor: "NAT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "NATURHOUSE HEALTH", valor: "NTH" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "NH HOTEL GROUP", valor: "NHH" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "NICOLAS CORREA", valor: "NEA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "NYESA VALORES", valor: "NYE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "OHL", valor: "OHL" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ORYZON GENOMICS", valor: "ORY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "PARQUES REUNIDOS", valor: "PQR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "PESCANOVA", valor: "PVA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "PHARMA MAR", valor: "PHM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "PRIM", valor: "PRM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "PRISA-A-", valor: "PRS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "PROSEGUR", valor: "PSG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "QUABIT IMMO", valor: "QBT" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "REALIA BUSINESS", valor: "RLIA" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "RED ELECTRICA", valor: "REE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "RENO DE MEDICI N", valor: "RDM" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "RENTA 4 BANCO", valor: "R4" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "RENTA CORPORACIO", valor: "REN" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "Repsol", valor: "REP" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "LABOR. FARMAC. R", valor: "ROVI" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "SACYR", valor: "SCYR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "expansion" , tag: "SAETA YIELD", valor: "SAY" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "Banco Santander", valor: "SAN" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "SIEM GAM REN EN", valor: "SGRE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "SNIACE", valor: "SNC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "SOLARIA ENERGIA", valor: "SLR" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "TALGO", valor: "TLGO" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "TECNICAS REUNIDA", valor: "TRE" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "TELEFONICA", valor: "TEF" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "TELEPIZZA GROUP", valor: "TPZ" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "TUBACEX", valor: "TUB" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "TUBOS REUNIDOS", valor: "TRG" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "URBAS GRUPO FIN.", valor: "UBS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "VERTICE 360", valor: "VER" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "VIDRALA", valor: "VID" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "Viscofan", valor: "VIS" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "VOCENTO", valor: "VOC" }).save();
    new Diccionario({ tipo: "ticker" ,  origen: "bolsamania" , tag: "ZARDOYA OTIS", valor: "ZOT" }).save();
    
};
