module.exports.pcbolsaAT = function () {

    'use strict'

    // Imports
    let metodos = require('./pcBolsaATvalor');

    // Definimos las correspondencias tiker->valor
    let valores = [
        { ticker: "ABG", url: "https://pcbolsa.com/AnalisisTecnico/Abengoa_-A-" },
        { ticker: "ABG.P", url: "https://pcbolsa.com/AnalisisTecnico/Abengoa_-B-" },
        { ticker: "ABE", url: "https://pcbolsa.com/AnalisisTecnico/Abertis" },
        { ticker: "ANA", url: "https://pcbolsa.com/AnalisisTecnico/Acciona" },
        { ticker: "ACX", url: "https://pcbolsa.com/AnalisisTecnico/Acerinox" },
        { ticker: "ACS", url: "https://pcbolsa.com/AnalisisTecnico/ACS" },
        { ticker: "ADZ", url: "https://pcbolsa.com/AnalisisTecnico/Adolfo_Dominguez" },
        { ticker: "ADV", url: "https://pcbolsa.com/AnalisisTecnico/Adveo" },
        { ticker: "AENA", url: "https://pcbolsa.com/AnalisisTecnico/AENA" },
        { ticker: "AIR", url: "https://pcbolsa.com/AnalisisTecnico/Airbus" },
        { ticker: "ALNT", url: "https://pcbolsa.com/AnalisisTecnico/Dinamia" },
        { ticker: "ALB", url: "https://pcbolsa.com/AnalisisTecnico/Corp_Fin_Alba" },
        { ticker: "ALM", url: "https://pcbolsa.com/AnalisisTecnico/Almirall" },
        { ticker: "AMS", url: "https://pcbolsa.com/AnalisisTecnico/Amadeus" },
        { ticker: "AMP", url: "https://pcbolsa.com/AnalisisTecnico/Amper" },
        { ticker: "APAM", url: "https://pcbolsa.com/AnalisisTecnico/Aperam_Reg" },
        { ticker: "APPS", url: "https://pcbolsa.com/AnalisisTecnico/Applus_Services" },
        { ticker: "MTS", url: "https://pcbolsa.com/AnalisisTecnico/ArcelorMittal" },
        { ticker: "A3M", url: "https://pcbolsa.com/AnalisisTecnico/Atresmedia" },
        { ticker: "ADX", url: "https://pcbolsa.com/AnalisisTecnico/Audax_Renovables" },
        { ticker: "AXIA", url: "https://pcbolsa.com/AnalisisTecnico/Axia_Real_Estate" },
        { ticker: "AZK", url: "https://pcbolsa.com/AnalisisTecnico/Azkoyen" },
        { ticker: "SAB", url: "https://pcbolsa.com/AnalisisTecnico/Banco_Sabadell" },
        { ticker: "BKIA", url: "https://pcbolsa.com/AnalisisTecnico/BANKIA" },
        { ticker: "BKT", url: "https://pcbolsa.com/AnalisisTecnico/Bankinter" },
        { ticker: "BDL", url: "https://pcbolsa.com/AnalisisTecnico/Baron_de_Ley" },
        { ticker: "CBAV", url: "https://pcbolsa.com/AnalisisTecnico/Clinica_Baviera" },
        { ticker: "BAY", url: "https://pcbolsa.com/AnalisisTecnico/Bayer" },
        { ticker: "BBVA", url: "https://pcbolsa.com/AnalisisTecnico/BBVA" },
        { ticker: "BIO", url: "https://pcbolsa.com/AnalisisTecnico/Biosearch" },
        { ticker: "RIO", url: "https://pcbolsa.com/AnalisisTecnico/Bodegas_Riojanas" },
        { ticker: "BAIN", url: "https://pcbolsa.com/AnalisisTecnico/Borges_Agri" },
        { ticker: "CABK", url: "https://pcbolsa.com/AnalisisTecnico/Caixabank" },
        { ticker: "CAM", url: "https://pcbolsa.com/AnalisisTecnico/CAM" },
        { ticker: "GCO", url: "https://pcbolsa.com/AnalisisTecnico/Grupo_Catalana_Occ" },
        { ticker: "CLNX", url: "https://pcbolsa.com/AnalisisTecnico/Cellnex_Telecom" },
        { ticker: "CIE", url: "https://pcbolsa.com/AnalisisTecnico/Cie_Automotive" },
        { ticker: "CLEO", url: "https://pcbolsa.com/AnalisisTecnico/Cleop" },
        { ticker: "CCE", url: "https://pcbolsa.com/AnalisisTecnico/Coca-Cola_Eur" },
        { ticker: "CDR", url: "https://pcbolsa.com/AnalisisTecnico/Codere" },
        { ticker: "CMC", url: "https://pcbolsa.com/AnalisisTecnico/Coemac" },
        { ticker: "CAF", url: "https://pcbolsa.com/AnalisisTecnico/CAF_Br" },
        { ticker: "COL", url: "https://pcbolsa.com/AnalisisTecnico/Inmob_Colonial" },
        { ticker: "OLE", url: "https://pcbolsa.com/AnalisisTecnico/Deoleo" },
        { ticker: "DIA", url: "https://pcbolsa.com/AnalisisTecnico/DIA" },
        { ticker: "DGI", url: "https://pcbolsa.com/AnalisisTecnico/Dogi_Int_Fabrics" },
        { ticker: "MDF", url: "https://pcbolsa.com/AnalisisTecnico/Duro_Felguera" },
        { ticker: "EBRO", url: "https://pcbolsa.com/AnalisisTecnico/Ebro_Foods" },
        { ticker: "EDR", url: "https://pcbolsa.com/AnalisisTecnico/EDreams" },
        { ticker: "ENO", url: "https://pcbolsa.com/AnalisisTecnico/Elecnor" },
        { ticker: "ENG", url: "https://pcbolsa.com/AnalisisTecnico/Enagas" },
        { ticker: "ENC", url: "https://pcbolsa.com/AnalisisTecnico/ENCE_Energia" },
        { ticker: "ELE", url: "https://pcbolsa.com/AnalisisTecnico/Endesa" },
        { ticker: "ECR", url: "https://pcbolsa.com/AnalisisTecnico/Ercros" },
        { ticker: "PAC", url: "https://pcbolsa.com/AnalisisTecnico/PAPELES_Y_CARTONES" },
        { ticker: "EKT", url: "https://pcbolsa.com/AnalisisTecnico/Euskaltel" },
        { ticker: "EZE", url: "https://pcbolsa.com/AnalisisTecnico/Grupo_Ezentis" },
        { ticker: "FAE", url: "https://pcbolsa.com/AnalisisTecnico/Faes_Farma" },
        { ticker: "FCC", url: "https://pcbolsa.com/AnalisisTecnico/FCC" },
        { ticker: "FER", url: "https://pcbolsa.com/AnalisisTecnico/Ferrovial" },
        { ticker: "FDR", url: "https://pcbolsa.com/AnalisisTecnico/Fluidra" },
        { ticker: "FUN", url: "https://pcbolsa.com/AnalisisTecnico/Funespana" },
        { ticker: "GALQ", url: "https://pcbolsa.com/AnalisisTecnico/GAM" },
        { ticker: "NTGY", url: "https://pcbolsa.com/AnalisisTecnico/Gas_Natural" },
        { ticker: "GEST", url: "https://pcbolsa.com/AnalisisTecnico/Gestamp_Autom_Br" },
        { ticker: "DOM", url: "https://pcbolsa.com/AnalisisTecnico/Global_Dominion" },
        { ticker: "GRF", url: "https://pcbolsa.com/AnalisisTecnico/Grifols_-A-" },
        { ticker: "GSJ", url: "https://pcbolsa.com/AnalisisTecnico/Grupo_San_Jose" },
        { ticker: "HIS", url: "https://pcbolsa.com/AnalisisTecnico/HISPANIA_ACTIVOS" },
        { ticker: "IAG", url: "https://pcbolsa.com/AnalisisTecnico/IAG" },
        { ticker: "IBE", url: "https://pcbolsa.com/AnalisisTecnico/Iberdrola" },
        { ticker: "IBG", url: "https://pcbolsa.com/AnalisisTecnico/Iberpapel" },
        { ticker: "ITX", url: "https://pcbolsa.com/AnalisisTecnico/Inditex" },
        { ticker: "IDR", url: "https://pcbolsa.com/AnalisisTecnico/Indra" },
        { ticker: "ISUR", url: "https://pcbolsa.com/AnalisisTecnico/Inmobiliaria_Sur" },
        { ticker: "INY", url: "https://pcbolsa.com/AnalisisTecnico/Inypsa" },
        { ticker: "RJF", url: "https://pcbolsa.com/AnalisisTecnico/LabReig_Jofre" },
        { ticker: "LRE", url: "https://pcbolsa.com/AnalisisTecnico/Lar_Espana" },
        { ticker: "LBK", url: "https://pcbolsa.com/AnalisisTecnico/Liberbank" },
        { ticker: "LGT", url: "https://pcbolsa.com/AnalisisTecnico/Lingotes_Especiales" },
        { ticker: "LOG", url: "https://pcbolsa.com/AnalisisTecnico/Logista" },
        { ticker: "MAP", url: "https://pcbolsa.com/AnalisisTecnico/Mapfre" },
        { ticker: "TL5", url: "https://pcbolsa.com/AnalisisTecnico/Mediaset_Espana" },
        { ticker: "MEL", url: "https://pcbolsa.com/AnalisisTecnico/Melia_Hotels" },
        { ticker: "MRL", url: "https://pcbolsa.com/AnalisisTecnico/Merlin_Prop" },
        { ticker: "MVC", url: "https://pcbolsa.com/AnalisisTecnico/Metrovacesa" },
        { ticker: "MCM", url: "https://pcbolsa.com/AnalisisTecnico/Miquel_y_Costas" },
        { ticker: "MTB", url: "https://pcbolsa.com/AnalisisTecnico/Montebalito" },
        { ticker: "NAT", url: "https://pcbolsa.com/AnalisisTecnico/Natra" },
        { ticker: "NTH", url: "https://pcbolsa.com/AnalisisTecnico/Naturhouse_Health" },
        { ticker: "NHH", url: "https://pcbolsa.com/AnalisisTecnico/NH_Hoteles" },
        { ticker: "NEA", url: "https://pcbolsa.com/AnalisisTecnico/Nicolas_Correa" },
        { ticker: "NYE", url: "https://pcbolsa.com/AnalisisTecnico/Nyesa_Valores" },
        { ticker: "OHL", url: "https://pcbolsa.com/AnalisisTecnico/OHL" },
        { ticker: "ORY", url: "https://pcbolsa.com/AnalisisTecnico/Oryzon_Genomics" },
        { ticker: "PQR", url: "https://pcbolsa.com/AnalisisTecnico/Parques_Reunidos" },
        { ticker: "PVA", url: "https://pcbolsa.com/AnalisisTecnico/Pescanova" },
        { ticker: "PHM", url: "https://pcbolsa.com/AnalisisTecnico/PHARMA_MAR" },
        { ticker: "PRM", url: "https://pcbolsa.com/AnalisisTecnico/Prim" },
        { ticker: "PRS", url: "https://pcbolsa.com/AnalisisTecnico/PRISA-A-" },
        { ticker: "PSG", url: "https://pcbolsa.com/AnalisisTecnico/Prosegur" },
        { ticker: "CASH", url: "https://pcbolsa.com/AnalisisTecnico/Prosegur_Cash_Br" },
        { ticker: "QBT", url: "https://pcbolsa.com/AnalisisTecnico/Quabit_Immo" },
        { ticker: "RLIA", url: "https://pcbolsa.com/AnalisisTecnico/Realia_Business" },
        { ticker: "REE", url: "https://pcbolsa.com/AnalisisTecnico/Red_Electrica" },
        { ticker: "REN", url: "https://pcbolsa.com/AnalisisTecnico/Renta_Corporacion" },
        { ticker: "RDM", url: "https://pcbolsa.com/AnalisisTecnico/Reno_De_Medici" },
        { ticker: "R4", url: "https://pcbolsa.com/AnalisisTecnico/Renta_4_Banco" },
        { ticker: "REP", url: "https://pcbolsa.com/AnalisisTecnico/REPSOL" },
        { ticker: "ROVI", url: "https://pcbolsa.com/AnalisisTecnico/Labor_Farmac_Rovi" },
        { ticker: "SCYR", url: "https://pcbolsa.com/AnalisisTecnico/Sacyr" },
        { ticker: "SAY", url: "https://pcbolsa.com/AnalisisTecnico/Saeta_Yield" },
        { ticker: "SAN", url: "https://pcbolsa.com/AnalisisTecnico/Banco_Santander" },
        { ticker: "SPS", url: "https://pcbolsa.com/AnalisisTecnico/Service_Point" },
        { ticker: "SGRE", url: "https://pcbolsa.com/AnalisisTecnico/Gamesa" },
        { ticker: "SNC", url: "https://pcbolsa.com/AnalisisTecnico/Sniace" },
        { ticker: "SLR", url: "https://pcbolsa.com/AnalisisTecnico/Solaria_Energia" },
        { ticker: "TLGO", url: "https://pcbolsa.com/AnalisisTecnico/Talgo" },
        { ticker: "TRE", url: "https://pcbolsa.com/AnalisisTecnico/Tecnicas_Reunidas" },
        { ticker: "TEF", url: "https://pcbolsa.com/AnalisisTecnico/Telefonica" },
        { ticker: "TPZ", url: "https://pcbolsa.com/AnalisisTecnico/Telepizza_Group" },
        { ticker: "TUB", url: "https://pcbolsa.com/AnalisisTecnico/Tubacex" },
        { ticker: "TRG", url: "https://pcbolsa.com/AnalisisTecnico/Tubos_Reunidos" },
        { ticker: "UNI", url: "https://pcbolsa.com/AnalisisTecnico/UNICAJA" },
        { ticker: "UBS", url: "https://pcbolsa.com/AnalisisTecnico/Urbas_Grupo_Fin" },
        { ticker: "VER", url: "https://pcbolsa.com/AnalisisTecnico/Vertice_360" },
        { ticker: "VID", url: "https://pcbolsa.com/AnalisisTecnico/Vidrala" },
        { ticker: "VIS", url: "https://pcbolsa.com/AnalisisTecnico/Viscofan" },
        { ticker: "VOC", url: "https://pcbolsa.com/AnalisisTecnico/Vocento_R" },
        { ticker: "ZOT", url: "https://pcbolsa.com/AnalisisTecnico/Zardoya_Otis" }
    ]

    // Carga analisis tecnico por cada valor
    valores.forEach(function (v, indice, array) {
        metodos.pcBolsaATvalor(v.ticker, v.url);
    });
}	
